version: '3.1'

services:


  sovcombank_redis:
    container_name: sovcombank_redis
    env_file:
      - .env
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./dbdata/redis:/var/lib/redis
    #      -./dockers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network


  sovcombank_postgres:
    container_name:  sovcombank_postgres
    hostname: postgresql
    image: postgres:14-alpine
    command: 
      - postgres
      - "-c"
      - "max_connections=2400"
      # повышает производительность, оптимально >=256MB
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "temp_buffers=10MB"
      # повышает производительность, оптимально >=1GB
      - "-c"
      - "maintenance_work_mem=1GB"
      - "-c"
      - "random_page_cost=0.1"
      - "-c"
      - "seq_page_cost=01"
      - "-c"
      - "checkpoint_completion_target=0.9"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      #POSTGRES_USER: $#POSTGRES_USER
      #POSTGRES_PASSWORD: $#POSTGRES_PASSWORD
      POSTGRES_DB: main
    volumes:
      - sovcombank_postgres:/var/lib/postgresql/data
      - ./auth/migrations/migrations.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./txs_mvp/migrations/01_create_initial_tables.up.sql:/docker-entrypoint-initdb.d/migration2.sql
    ports:
      - "5517:5432"
    networks:
      - app-network


  auth_api:
    container_name: auth_api
    build:
      context: ./auth/
      dockerfile: ../dockers/python/Dockerfile
    command: sh -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - .env
      - ./auth/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./auth:/app
    networks:
      - app-network
    depends_on:
      - sovcombank_redis
      - sovcombank_postgres

  sovcombank_courses:
    container_name: sovcombank_courses
    build:
      context: ./courses_api/app/
      dockerfile: ../../dockers/python/Dockerfile
    #command: /bin/bash -c "python -m pip install -r /app/requirements.txt --no-cache-dir && python api.py"
    command: /bin/bash -c "python api.py"
    restart: unless-stopped
    ports:
      - "3200:3000"
    env_file:
      - .env
      - ./courses_api/app/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./courses_api/app/:/app
    networks:
      - app-network
    depends_on:
      - sovcombank_redis
      - sovcombank_postgres
      - auth_api

  sovcombank_frontend:
    #image: 16.18
    image: node:16.18-alpine3.15
    container_name: sovcombank_frontend
    # build:
    #   context: ./apps/otherlangs/node/natural
    #   dockerfile: ../../../../dockers/node/Dockerfile
    env_file:
      - .env
      #- ./app/.env
    #command: npm i && node index2.js
    command: sh -c "cd /app && npm i && npm start"
    restart: unless-stopped
    # ports:
    #   - "3001:3000"
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./frontend:/app
    network_mode: host
    # depends_on:
    #   - sovcombank_redis
    #   - sovcombank_postgres


networks:
  app-network:
    driver: bridge

volumes:
  sovcombank_postgres:
    driver: local
