version: '3.1'

services:

  auth_api:
    container_name: auth_api
    build:
      context: ./auth/
      dockerfile: ../dockers/python/Dockerfile
    command: sh -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - .env
      - ./auth/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./auth:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   sovcombank_postgres:
#     driver: local
