version: '3.1'

services:


  
  auth_api:
    container_name: auth_api
    build:
      context: ./auth/
      dockerfile: ../dockers/python/Dockerfile
    command: sh -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 3000"
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - .env
      - ./auth/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./auth:/app
    networks:
      - app-network
    # depends_on:
    #   - sovcombank_redis
    #   - sovcombank_postgres

  sovcombank_courses:
    container_name: sovcombank_courses
    build:
      context: ./courses_api/app/
      dockerfile: ../../dockers/python/Dockerfile
    #command: /bin/bash -c "python -m pip install -r /app/requirements.txt --no-cache-dir && python api.py"
    command: /bin/bash -c "python api.py"
    restart: unless-stopped
    ports:
      - "3200:3000"
    env_file:
      - .env
      - ./courses_api/app/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./courses_api/app/:/app
    networks:
      - app-network
    depends_on:
 
      - auth_api

  sovcombank_txs:
    container_name: sovcombank_txs
    build:
      context: ./txs_mvp/app/
      dockerfile: ../../dockers/python/Dockerfile
    #command: /bin/bash -c "python -m pip install -r /app/requirements.txt --no-cache-dir && python api.py"
    command: /bin/bash -c "python api.py"
    restart: unless-stopped
    ports:
      - "3300:3000"
    env_file:
      - .env
      - ./txs_mvp/app/.env
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    volumes:
      - ./txs_mvp/app/:/app
    networks:
      - app-network
    depends_on:
      - auth_api


networks:
  app-network:
    driver: bridge

volumes:
  sovcombank_postgres:
    driver: local
