version: '3.1'

services:


  sovcombank_redis:
    container_name: sovcombank_redis
    env_file:
      - .env
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./dbdata/redis:/var/lib/redis
    #      -./dockers/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  sovcombank_postgres:
    container_name:  sovcombank_postgres
    hostname: postgresql
    image: postgres:14-alpine
    command: 
      - postgres
      - "-c"
      - "max_connections=2400"
      # повышает производительность, оптимально >=256MB
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "temp_buffers=10MB"
      # повышает производительность, оптимально >=1GB
      - "-c"
      - "maintenance_work_mem=1GB"
      - "-c"
      - "random_page_cost=0.1"
      - "-c"
      - "seq_page_cost=01"
      - "-c"
      - "checkpoint_completion_target=0.9"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      #POSTGRES_USER: $#POSTGRES_USER
      #POSTGRES_PASSWORD: $#POSTGRES_PASSWORD
      POSTGRES_DB: main
    volumes:
      - sovcombank_postgres:/var/lib/postgresql/data
      - ./auth/migrations/migrations.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./txs_mvp/migrations/01_create_initial_tables.up.sql:/docker-entrypoint-initdb.d/migration2.sql
    ports:
      - "5517:5432"
    networks:
      - app-network

# networks:
#   app-network:
#     external:
#       name: sender_app-network

networks:
  app-network:
    driver: bridge

volumes:
  sovcombank_postgres:
    driver: local
